apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage0
provisioner: nfs-storage # must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
