apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner0
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner0
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner0-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client-provisioner0
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner0
    # replace with namespace where provisioner is deployed
    namespace: nfs-provisioner0
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner0-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner0
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner0
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner0
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner0
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner0
    # replace with namespace where provisioner is deployed
    namespace: nfs-provisioner0
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner0
  apiGroup: rbac.authorization.k8s.io
